# Sample docker-compose for serve simple metrics and Grafana
---
services:
  influxdb:
    container_name: influxdb
    hostname: influxdb
    image: influxdb:latest
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - influxdb_storage:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    environment:
# Uncomment the INIT_MODE var to run it in setup at the first time
#      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXD_STORAGE_CACHE_MAX_MEMORY_SIZE=${INFLUXD_STORAGE_CACHE_MAX_MEMORY_SIZE}
      - INFLUXD_STORAGE_CACHE_SNAPSHOT_MEMORY_SIZE=${INFLUXD_STORAGE_CACHE_SNAPSHOT_MEMORY_SIZE}
      - INFLUXD_STORAGE_CACHE_SNAPSHOT_WRITE_COLD_DURATION=${INFLUXD_STORAGE_CACHE_SNAPSHOT_WRITE_COLD_DURATION}
      - INFLUXD_STORAGE_COMPACT_FULL_WRITE_COLD_DURATION=${INFLUXD_STORAGE_COMPACT_FULL_WRITE_COLD_DURATION}
      - INFLUXD_STORAGE_RETENTION_CHECK_INTERVAL=${INFLUXD_STORAGE_RETENTION_CHECK_INTERVAL}
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "1"

#  chronograf:
#    container_name: chronograf
#    hostname: chronograf
#    image: chronograf:latest
#    restart: always
#    ports:
#      - "8888:8888"
#    volumes:
#      - chronograf_storage:/var/lib/chronograf
#    depends_on:
#      - influxdb
#    environment:
#      - INFLUXDB_URL="http://influxdb:8086"
#      - INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
#      - INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
#    deploy:
#      resources:
#        limits:
#          memory: 512M
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "1M"
#        max-file: "1"

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    volumes:
      - grafana_data:/var/lib/grafana
    deploy:
      resources:
        limits:
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "1"

  pp-code-metrics:
    container_name: pp-code-metrics
    hostname: pp-code-metrics
    image: neofob/pp-code-metrics:latest
    restart: always
    depends_on:
      - influxdb
      - temper
    environment:
      - INTERVAL=10
    volumes:
      - ./my_settings.yml:/opt/pp-code-metrics/my_settings.yml:ro
      - ./crontab/pp-code-metrics.tmpl:/etc/cron.d/pp-code-metrics.tmpl
    deploy:
      resources:
        limits:
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "1"

  temper:
    container_name: temper
    hostname: temper
    image: temper/service:latest
    restart: always
    volumes:
      - /dev:/dev
    ports:
      - 2610:2610
    privileged: true
    deploy:
      resources:
        limits:
          memory: 32M
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "1"

volumes:
  chronograf_storage:
    external: true
  influxdb_storage:
    external: true
  influxdb_config:
    external: true
  grafana_data:
    external: true
